### ISSUE TITLE
Issue using qgepqwat2ili via console on docker qgis

### ISSUE THREAD

**Issue by meierrom** [QGEP/qgepqwat2ili#109]
Hi folks,

I'm getting the following error running an export via console:

python -m qgepqwat2ili qgep export /data/my_export.xtf

INFO	CONNECTING TO DATABASE...
INFO	Schema pg2ili_abwasser already exists, we truncate instead
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgepplugin/qgepqwat2ili/qgepqwat2ili/__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgepplugin/qgepqwat2ili/qgepqwat2ili/__init__.py", line 137, in main
    qgep_export(selection=args.selection.split(",") if args.selection else None, labels_file=args.labels_file)
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgepplugin/qgepqwat2ili/qgepqwat2ili/qgep/export.py", line 22, in qgep_export
    ABWASSER = get_abwasser_model()
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgepplugin/qgepqwat2ili/qgepqwat2ili/qgep/model_abwasser.py", line 185, in get_abwasser_model
    utils.sqlalchemy.prepare_automap_base(Base, SCHEMA)
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgepplugin/qgepqwat2ili/qgepqwat2ili/utils/sqlalchemy.py", line 62, in prepare_automap_base
    base.prepare(
  File "<string>", line 2, in prepare
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/ext/automap.py", line 1346, in prepare
    map_config.map()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/decl_base.py", line 1981, in map
    return super().map(mapper_kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/decl_base.py", line 1888, in map
    mapper_cls(self.cls, self.local_table, **self.mapper_args),
  File "<string>", line 2, in __init__
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/mapper.py", line 863, in __init__
    self._configure_pks()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/mapper.py", line 1648, in _configure_pks
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapper Mapper[baseclass(baseclass)] could not assemble any primary key columns for mapped table 'baseclass'

Any ideas what's going wrong?

Kind regards,
Roman

**Comment by sjib** [comment]
@meierrom Is `/data/my_export.xtf` a valid path on your system?
