### ISSUE TITLE
Export: Error when password not set in pg_conf

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/qgepqwat2ili#110]
Does not work with QGEP Plugin 1.6.0-rc.4, if there is no password in the pg_service.conf:
KAU is not the database, KAU is the username!

Ein Fehler trat bei der Ausführung von Python-Code auf:

psycopg2.OperationalError: connection to server at "xxxx" (nnn.nnn.nn.nn), port 5432 failed: FATAL: database "KAU" does not exist
Traceback (most recent call last):
File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui_init_.py", line 197, in action_do_export
create_ili_schema(
File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\ili2db.py", line 13, in create_ili_schema
connection = psycopg2.connect(get_pgconf_as_psycopg2_dsn())
File "C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\psycopg2_init_.py", line 127, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "xxxx" (nnn.nnn.nn.nn), port 5432 failed: FATAL: database "KAU" does not exist

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS-Version: 3.28.2-Firenze Firenze, b47e00ba601

Python-Pfad:
C:/PROGRA1/QGIS3/apps/qgis/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA1/QGIS3/apps/qgis/./python/plugins
C:\Program Files\QGIS3\bin\python39.zip
C:\PROGRA1\QGIS3\apps\Python39\DLLs
C:\PROGRA1\QGIS3\apps\Python39\lib
C:\Program Files\QGIS3\bin
C:\Users\KAU\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA1\QGIS3\apps\Python39
C:\PROGRA1\QGIS3\apps\Python39\lib\site-packages
C:\PROGRA1\QGIS3\apps\Python39\lib\site-packages\win32
C:\PROGRA1\QGIS3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python
P:/Thun/Gemeinden/246 Krattigen/O1379 GEP Krattigen/qgep
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui....

**Comment by urskaufmann** [comment]
It's not the same error as #76
