### ISSUE TITLE
Error upon import

### ISSUE THREAD

**Issue by meierrom** [QGEP/qgepqwat2ili#122]
Hi folks,

I'm getting the following error message upon issuing an import command:

python -m qgepqwat2ili qgep import /data/arbon/my_export_sia405.xtf --log

[...]
INFO	EXECUTING: "java" -jar "/*/ili2pg-4.5.0.jar" --import --deleteData --dbhost "10.0.2.2" --dbport "*" --dbusr "***" --dbpwd "***" --dbdatabase "*" --dbschema "pg2ili_abwasser" --modeldir "/*/ili" --disableValidation --skipReferenceErrors --createTidCol --noSmartMapping --defaultSrsCode 2056 --log "/*/my_export_sia405.xtf.230503105941.iliimport.log" "/*/my_export_sia405.xtf"
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/*/qgepqwat2ili/__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "/*/qgepqwat2ili/__init__.py", line 175, in main
    qgep_import()
  File "/*/qgepqwat2ili/qgep/import_.py", line 30, in qgep_import
    pre_session.execute("SELECT qgep_sys.drop_symbology_triggers();")
  File "/*/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/*/sqlalchemy/orm/session.py", line 2022, in _execute_internal
    statement = coercions.expect(roles.StatementRole, statement)
  File "/*/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/*/sqlalchemy/sql/coercions.py", line 639, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
  File "/*/sqlalchemy/sql/coercions.py", line 632, in _text_coercion
    return _no_text_coercion(element, argname)
  File "/*/sqlalchemy/sql/coercions.py", line 602, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'SELECT qgep_sys.drop_symb...' should be explicitly declared as text('SELECT qgep_sys.drop_symb...')

Any ideas what's going wrong?

Kind regards,
Roman

**Comment by sjib** [comment]
@meierrom I think you have not set the flag  `--pgservice PGSERVICE`, so there is no info to connect with your database

`usage: python -m qgepqwat2ili qwat [-h] [--recreate_schema] [--skip_validation] [--pgservice PGSERVICE] [--log] [--include_hydraulics] {import,export} path`
