### ISSUE TITLE
INTERLIS Export QGEP - Error if identifier isNull

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#31]
![20210824_wastewater_structure identifier_empty_message](https://user-images.githubusercontent.com/1265865/130629581-1d568da3-c90a-4bf1-8135-61885218c345.jpg)

Ein Fehler trat bei der Ausführung von Python-Code auf: 

sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) FEHLER:  NULL-Wert in Spalte »bezeichnung« verletzt Not-Null-Constraint DETAIL:  Fehlgeschlagene Zeile enthält (25, null, 1800, Z2, null, null, null, null, null, null, null, null, mittelfristig, null, in_Betrieb, null, null, null, null, null, null, null). [SQL: INSERT INTO pg2ili_abwasser.abwasserbauwerk (t_id, akten, baujahr, baulicherzustand, baulos, bemerkung, bezeichnung, bruttokosten, detailgeometrie, ersatzjahr, finanzierung, inspektionsintervall, sanierungsbedarf, standortname, astatus, subventionen, wbw_basisjahr, wbw_bauart, wiederbeschaffungswert, zugaenglichkeit, betreiberref, eigentuemerref) VALUES (%(t_id)s, %(akten)s, %(baujahr)s, %(baulicherzustand)s, %(baulos)s, %(bemerkung)s, %(bezeichnung)s, %(bruttokosten)s, ST_Force2D(NULL), %(ersatzjahr)s, %(finanzierung)s, %(inspektionsintervall)s, %(sanierungsbedarf)s, %(standortname)s, %(astatus)s, %(subventionen)s, %(wbw_basisjahr)s, %(wbw_bauart)s, %(wiederbeschaffungswert)s, %(zugaenglichkeit)s, %(betreiberref)s, %(eigentuemerref)s)] [parameters: {'t_id': 25, 'akten': None, 'baujahr': 1800, 'baulicherzustand': 'Z2', 'baulos': None, 'bemerkung': None, 'bezeichnung': None, 'bruttokosten': None, 'ersatzjahr': None, 'finanzierung': None, 'inspektionsintervall': None, 'sanierungsbedarf': 'mittelfristig', 'standortname': None, 'astatus': 'in_Betrieb', 'subventionen': None, 'wbw_basisjahr': None, 'wbw_bauart': None, 'wiederbeschaffungswert': None, 'zugaenglichkeit': None, 'betreiberref': None, 'eigentuemerref': None}] (Background on this error at: http://sqlalche.me/e/13/gkpj) 
Traceback (most recent call last):
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: FEHLER:  NULL-Wert in Spalte »bezeichnung« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (25, null, 1800, Z2, null, null, null, null, null, null, null, null, mittelfristig, null, in_Betrieb, null, null, null, null, null, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 173, in action_do_export
    qgep_export(selection=export_dialog.selected_ids)
  File "C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\qgep\export.py", line 200, in qgep_export
    abwasser_session.flush()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    insert,
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\persistence.py", line 1132, in _emit_insert_statements
    statement.values(value_params), params
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) FEHLER:  NULL-Wert in Spalte »bezeichnung« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (25, null, 1800, Z2, null, null, null, null, null, null, null, null, mittelfristig, null, in_Betrieb, null, null, null, null, null, null, null).

[SQL: INSERT INTO pg2ili_abwasser.abwasserbauwerk (t_id, akten, baujahr, baulicherzustand, baulos, bemerkung, bezeichnung, bruttokosten, detailgeometrie, ersatzjahr, finanzierung, inspektionsintervall, sanierungsbedarf, standortname, astatus, subventionen, wbw_basisjahr, wbw_bauart, wiederbeschaffungswert, zugaenglichkeit, betreiberref, eigentuemerref) VALUES (%(t_id)s, %(akten)s, %(baujahr)s, %(baulicherzustand)s, %(baulos)s, %(bemerkung)s, %(bezeichnung)s, %(bruttokosten)s, ST_Force2D(NULL), %(ersatzjahr)s, %(finanzierung)s, %(inspektionsintervall)s, %(sanierungsbedarf)s, %(standortname)s, %(astatus)s, %(subventionen)s, %(wbw_basisjahr)s, %(wbw_bauart)s, %(wiederbeschaffungswert)s, %(zugaenglichkeit)s, %(betreiberref)s, %(eigentuemerref)s)]
[parameters: {'t_id': 25, 'akten': None, 'baujahr': 1800, 'baulicherzustand': 'Z2', 'baulos': None, 'bemerkung': None, 'bezeichnung': None, 'bruttokosten': None, 'ersatzjahr': None, 'finanzierung': None, 'inspektionsintervall': None, 'sanierungsbedarf': 'mittelfristig', 'standortname': None, 'astatus': 'in_Betrieb', 'subventionen': None, 'wbw_basisjahr': None, 'wbw_bauart': None, 'wiederbeschaffungswert': None, 'zugaenglichkeit': None, 'betreiberref': None, 'eigentuemerref': None}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.16.4-Hannover Hannover, 654e76b3cb 

Python-Pfad:
C:/PROGRA~1/QGIS 3.16/apps/qgis-ltr/./python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS 3.16\apps\Python37
C:\PROGRA~1\QGIS 3.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS 3.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\Users\Stefan\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Daten/QGEP
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
.

**Comment by sjib** [comment]
From the model perspective this is correct as each Bezeichnung is set to MANDATORY. When I check in the data I get line where identifiers are empty:
![20210824_wastewater_structure identifier_empty](https://user-images.githubusercontent.com/1265865/130628827-4176480a-c1f5-4405-b55f-a90d7bb3b7fa.jpg)

From a user perspective it is not yet very convenienct to find this out from the error message above, but technically it is correct.
